### ISSUE TITLE
1.oceanbase-database -> 2.compatibility-with-mysql.md -> 备份恢复 小节不完整

### ISSUE THREAD

**Issue by dongdxf** [oceanbase/oceanbase-doc#12]
备份恢复

OceanBase 数据库兼容了部分 MySQL 数据库的备份恢复特性，主要支持情况如下：

<内容缺失>

**Comment by MeinaWang** [comment]
已补充，https://open.oceanbase.com/docs/observer-cn/V3.1.3/0000000000160109
