### ISSUE TITLE
文档缺少各虚拟表作用和字段的含义

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase-doc#14]
__all_virtual_processlist
__all_virtual_core_meta_table
__all_virtual_zone_stat
__all_virtual_plan_cache_stat
__all_virtual_plan_stat
__all_virtual_mem_leak_checker_info
__all_virtual_latch
__all_virtual_kvcache_info
__all_virtual_data_type_class
__all_virtual_data_type
__all_virtual_server_stat
__all_virtual_rebalance_task_stat
__all_virtual_session_event
__all_virtual_session_wait
__all_virtual_session_wait_history
__all_virtual_system_event
__all_virtual_tenant_memstore_info
__all_virtual_concurrency_object_pool
__all_virtual_sesstat
__all_virtual_sysstat
__all_virtual_storage_stat
__all_virtual_disk_stat
__all_virtual_memstore_info
__all_virtual_partition_info
__all_virtual_upgrade_inspection
__all_virtual_trans_stat
__all_virtual_trans_mgr_stat
__all_virtual_election_info
__all_virtual_election_mem_stat
__all_virtual_sql_audit
__all_virtual_trans_mem_stat
__all_virtual_partition_sstable_image_info
__all_virtual_core_root_table
__all_virtual_core_all_table
__all_virtual_core_column_table
__all_virtual_memory_info
__all_virtual_tenant_stat
__all_virtual_sys_parameter_stat
__all_virtual_partition_replay_status
__all_virtual_clog_stat
__all_virtual_trace_log
__all_virtual_engine
__all_virtual_proxy_server_stat
__all_virtual_proxy_sys_variable
__all_virtual_proxy_schema
__all_virtual_plan_cache_plan_explain
__all_virtual_obrpc_stat
__all_virtual_partition_sstable_merge_info
__all_virtual_sql_monitor
__all_virtual_sql_plan_statistics
__all_virtual_partition_sstable_macro_info
__all_virtual_proxy_partition_info
__all_virtual_proxy_partition
__all_virtual_proxy_sub_partition
__all_virtual_proxy_route
__all_virtual_rebalance_tenant_stat
__all_virtual_rebalance_unit_stat
__all_virtual_rebalance_replica_stat
__all_virtual_partition_amplification_stat
__all_virtual_election_event_history
__all_virtual_partition_store_info
__all_virtual_leader_stat
__all_virtual_partition_migration_status
__all_virtual_sys_task_status
__all_virtual_macro_block_marker_status
__all_virtual_server_clog_stat
__all_virtual_rootservice_stat
__all_virtual_election_priority
__all_virtual_tenant_disk_stat
__all_virtual_rebalance_map_stat
__all_virtual_rebalance_map_item_stat
__all_virtual_io_stat
__all_virtual_long_ops_status
__all_virtual_rebalance_unit_migrate_stat
__all_virtual_rebalance_unit_distribution_stat
__all_virtual_server_object_pool
__all_virtual_trans_lock_stat
__all_virtual_election_group_info
__all_virtual_server_blacklist
__all_virtual_partition_split_info
__all_virtual_trans_result_info_stat
__all_virtual_duplicate_partition_mgr_stat
__all_virtual_tenant_parameter_stat
__all_virtual_server_schema_info
__all_virtual_memory_context_stat
__all_virtual_dump_tenant_info
__all_virtual_tenant_parameter_info
__all_virtual_dag_warning_history
__all_virtual_master_key_version_info
__all_virtual_server_memory_info
__all_virtual_partition_table
__all_virtual_lock_wait_stat
__all_virtual_partition_item
__all_virtual_replica_task
__all_virtual_partition_location
__all_virtual_tenant_memstore_allocator_info
__all_virtual_table_mgr
__all_virtual_meta_table
__all_virtual_freeze_info
__all_virtual_bad_block_table
__all_virtual_px_worker_stat
__all_virtual_trans_audit
__all_virtual_trans_sql_audit
__all_virtual_weak_read_stat
__all_virtual_partition_audit
__all_virtual_sequence_v2
__all_virtual_sequence_value
__all_virtual_cluster
__all_virtual_partition_table_store_stat
__all_virtual_ddl_operation
__all_virtual_outline
__all_virtual_outline_history
__all_virtual_synonym
__all_virtual_synonym_history
__all_virtual_database_privilege
__all_virtual_database_privilege_history
__all_virtual_table_privilege
__all_virtual_table_privilege_history
__all_virtual_database
__all_virtual_database_history
__all_virtual_tablegroup
__all_virtual_tablegroup_history
__all_virtual_table
__all_virtual_table_history
__all_virtual_column
__all_virtual_column_history
__all_virtual_part
__all_virtual_part_history
__all_virtual_part_info
__all_virtual_part_info_history
__all_virtual_def_sub_part
__all_virtual_def_sub_part_history
__all_virtual_sub_part
__all_virtual_sub_part_history
__all_virtual_constraint
__all_virtual_constraint_history
__all_virtual_foreign_key
__all_virtual_foreign_key_history
__all_virtual_foreign_key_column
__all_virtual_foreign_key_column_history
__all_virtual_temp_table
__all_virtual_ori_schema_version
__all_virtual_sys_stat
__all_virtual_user
__all_virtual_user_history
__all_virtual_sys_variable
__all_virtual_sys_variable_history
__all_virtual_func
__all_virtual_func_history
__all_virtual_package
__all_virtual_package_history
__all_virtual_routine
__all_virtual_routine_history
__all_virtual_routine_param
__all_virtual_routine_param_history
__all_virtual_type
__all_virtual_type_history
__all_virtual_type_attr
__all_virtual_type_attr_history
__all_virtual_coll_type
__all_virtual_coll_type_history
__all_virtual_column_stat
__all_virtual_table_stat
__all_virtual_histogram_stat
__all_virtual_column_statistic
__all_virtual_recyclebin
__all_virtual_tenant_gc_partition_info
__all_virtual_tenant_plan_baseline
__all_virtual_tenant_plan_baseline_history
__all_virtual_sequence_object
__all_virtual_sequence_object_history
__all_virtual_raid_stat
__all_virtual_server_log_meta
__all_virtual_dtl_channel
__all_virtual_dtl_memory
__all_virtual_dtl_first_cached_buffer
__all_virtual_dblink
__all_virtual_dblink_history
__all_virtual_tenant_partition_meta_table
__all_virtual_tenant_role_grantee_map
__all_virtual_tenant_role_grantee_map_history
__all_virtual_tenant_keystore
__all_virtual_tenant_keystore_history
__all_virtual_deadlock_stat
__all_virtual_tenant_tablespace
__all_virtual_tenant_tablespace_history
__ALL_VIRTUAL_INFORMATION_COLUMNS
__all_virtual_pg_partition_info
__all_virtual_tenant_user_failed_login_stat
__all_virtual_tenant_profile
__all_virtual_tenant_profile_history
__all_virtual_security_audit
__all_virtual_security_audit_history
__all_virtual_trigger
__all_virtual_trigger_history
__all_virtual_cluster_stats
__all_virtual_sstable_column_checksum
__all_virtual_ps_stat
__all_virtual_ps_item_info
__all_virtual_sql_workarea_history_stat
__all_virtual_sql_workarea_active
__all_virtual_sql_workarea_histogram
__all_virtual_sql_workarea_memory_info
__all_virtual_security_audit_record
__all_virtual_sysauth
__all_virtual_sysauth_history
__all_virtual_objauth
__all_virtual_objauth_history
__all_virtual_backup_info
__all_virtual_backup_task
__all_virtual_pg_backup_task
__all_virtual_pg_backup_log_archive_status
__all_virtual_server_backup_log_archive_status
__all_virtual_error
__all_virtual_timestamp_service
__all_virtual_table_modifications
__all_virtual_backup_clean_info
__all_virtual_restore_pg_info
__all_virtual_object_type
__all_virtual_trans_table_status
__all_virtual_pg_log_archive_stat
__all_virtual_sql_plan_monitor
__all_virtual_sql_monitor_statname
__all_virtual_open_cursor
__all_virtual_backup_validation_task
__all_virtual_pg_backup_validation_task
__all_virtual_time_zone
__all_virtual_time_zone_name
__all_virtual_time_zone_transition
__all_virtual_time_zone_transition_type
__all_virtual_constraint_column
__all_virtual_constraint_column_history
__all_virtual_files
__all_virtual_dependency
__all_virtual_reserved_table_mgr
__all_virtual_backupset_history_mgr
__all_virtual_backup_backupset_task
__all_virtual_pg_backup_backupset_task
__all_virtual_global_transaction

**Comment by longdafeng** [comment]
理论上, 这些内部虚拟表都是内部debug 和监控使用, 因为, 他们经常性因为内部设计的变动而发生改变, 现在不打算公开

如果需要对部分表有强烈诉求, 就提出来, 我们将这些表expose 出来, 作为一个接口固化下来
