### ISSUE TITLE
文档的所有链接均不能正常链接到目标地址

### ISSUE THREAD

**Issue by ChrisYuan** [oceanbase/oceanbase-doc#27]
文章内部所有的参考链接，功能为跳转到本文档的另一部分的，均不能正常链接到目的地址；现在点击是跳转到MD文件上，但是并不能在网页端正常显示。如下：

<img width="704" alt="image" src="https://user-images.githubusercontent.com/2404284/163892233-675f0005-e21c-444b-8bb7-0a3cb05d7a9b.png">

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/2404284/163892324-8f7d647b-86c7-483b-9c79-f254652eb202.png">

**Comment by MeinaWang** [comment]
已经修复，https://open.oceanbase.com/docs/observer-cn/V3.1.3/10000000000096602
