### ISSUE TITLE
性能优化部分, 需要增加机器部署架构

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase-doc#312]
比如在tpcc/sysbench/tpch 性能测试中,

建议机器规格

其中可能需要有个公式, 算出ecs 1 需要多少资源, 比如如果想跑更高并发数, ecs1 可能需要更高的配置
ecs1: 8核/64g内存/essd 磁盘1快                  部署tpcc/sysbench/tpch 客户端程序 + obproxy + obdeploy
ecs2: 32核/256g 内存/essd 磁盘2块            部署observer
ecs3: 32核/256g 内存/essd 磁盘2块            部署observer
ecs4: 32核/256g 内存/essd 磁盘2块            部署observer

**Comment by yuhuangwmn** [comment]
在压测中，服务器配置与并发数并不是一个线性关系，无法通过公式比较好的算出需要多少资源
