### ISSUE TITLE
[Bug]: 永久关闭透明大页 和 NUMA方法（CentOS 或 Red Hat 7/8）

### ISSUE THREAD

**Issue by YuentsingLeung** [oceanbase/oceanbase-doc#328]
### Please check the issue list for the same bug

- [X] Please check issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
- Version or commit id.
- Hardware parameter: OS type & Compiler & CPU etc. 
- Others

OceanBase官网址中的手动关闭透明大页方法可能有问题的，而且此方法是临时的，不是永久的，重启OS会失效。
https://www.oceanbase.com/docs/community-observer-cn-10000000000900489
对于 CentOS 或 Red Hat 操作系统，需要运行以下命令，手动关闭透明大页：
echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled

临时关闭透明大页正确语法是 ：
 echo never > /sys/kernel/mm/transparent_hugepage/enabledecho never > /sys/kernel/mm/transparent_hugepage/defrag


建议永久关闭透明大页 和 NUMA（CentOS 或 Red Hat 7/8）：
sed -i 's/quiet/quiet transparent_hugepage=never numa=off/' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg
```

### Fast Reproduce Steps (Required)

OceanBase官网址中的手动关闭透明大页方法可能有问题的，而且此方法是临时的，不是永久的，重启OS会失效。
https://www.oceanbase.com/docs/community-observer-cn-10000000000900489
对于 CentOS 或 Red Hat 操作系统，需要运行以下命令，手动关闭透明大页：
echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled

临时关闭透明大页正确语法是 ：
 echo never > /sys/kernel/mm/transparent_hugepage/enabledecho never > /sys/kernel/mm/transparent_hugepage/defrag

建议永久关闭透明大页 和 NUMA（CentOS 或 Red Hat 7/8）：
sed -i 's/quiet/quiet transparent_hugepage=never numa=off/' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg

### Actual Behavior

OceanBase官网址中的手动关闭透明大页方法可能有问题的，而且此方法是临时的，不是永久的，重启OS会失效。
https://www.oceanbase.com/docs/community-observer-cn-10000000000900489
对于 CentOS 或 Red Hat 操作系统，需要运行以下命令，手动关闭透明大页：
echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled

临时关闭透明大页正确语法是 ：
 echo never > /sys/kernel/mm/transparent_hugepage/enabledecho never > /sys/kernel/mm/transparent_hugepage/defrag

建议永久关闭透明大页 和 NUMA（CentOS 或 Red Hat 7/8）：
sed -i 's/quiet/quiet transparent_hugepage=never numa=off/' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg

### Expected Behavior

OceanBase官网址中的手动关闭透明大页方法可能有问题的，而且此方法是临时的，不是永久的，重启OS会失效。
https://www.oceanbase.com/docs/community-observer-cn-10000000000900489
对于 CentOS 或 Red Hat 操作系统，需要运行以下命令，手动关闭透明大页：
echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled

临时关闭透明大页正确语法是 ：
 echo never > /sys/kernel/mm/transparent_hugepage/enabledecho never > /sys/kernel/mm/transparent_hugepage/defrag

建议永久关闭透明大页 和 NUMA（CentOS 或 Red Hat 7/8）：
sed -i 's/quiet/quiet transparent_hugepage=never numa=off/' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg

### other information

OceanBase官网址中的手动关闭透明大页方法可能有问题的，而且此方法是临时的，不是永久的，重启OS会失效。
https://www.oceanbase.com/docs/community-observer-cn-10000000000900489
对于 CentOS 或 Red Hat 操作系统，需要运行以下命令，手动关闭透明大页：
echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled

临时关闭透明大页正确语法是 ：
 echo never > /sys/kernel/mm/transparent_hugepage/enabledecho never > /sys/kernel/mm/transparent_hugepage/defrag

建议永久关闭透明大页 和 NUMA（CentOS 或 Red Hat 7/8）：
sed -i 's/quiet/quiet transparent_hugepage=never numa=off/' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg

**Comment by yuhuangwmn** [comment]
Updated related doc. https://www.oceanbase.com/docs/community-observer-cn-10000000000900489
