### ISSUE TITLE
[Doc]: 内容重复

### ISSUE THREAD

**Issue by bigdata2018** [oceanbase/oceanbase-doc#331]
### Check Before Asking

- [X] Please check the issue list and confirm this issue is encountered for the first time.

### Description

快速上手=》体验多租户特性=》根据创建的 resource pool 创建租户
存在如下重复字段：
在完成 tenant1、tenant2 租户创建后，您可以通过查询 oceanbase.DBA_OB_TENANTS 视图来确认租户是否创建成功。

obclient [oceanbase]> SELECT * FROM DBA_OB_TENANTS;
在完成 tenant1、tenant2 租户创建后，您可以通过查询 oceanbase.DBA_OB_TENANTS 视图来确认租户是否创建成功。

obclient [oceanbase]> SELECT * FROM DBA_OB_TENANTS;

### Documentation Links

https://www.oceanbase.com/docs/community-observer-cn-10000000000900959

### Are you willing to submit a pull request?

- [X] Yes I am willing to submit a pull request.

**Comment by yuhuangwmn** [comment]
Problem fixed
