### ISSUE TITLE
[Doc]: Add requirement for MySQL authority

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase-doc#337]
### Check Before Asking

- [X] Please check the issue list and confirm this issue is encountered for the first time.

### Description

oms mysql作为数据源，开启增量同步的用户权限需要有create/insert/update 心跳表的权限

### Documentation Links

https://www.oceanbase.com/docs/community-oms-cn-10000000000818595

### Are you willing to submit a pull request?

- [X] Yes I am willing to submit a pull request.

**Comment by yuhuangwmn** [comment]
fixed
