### ISSUE TITLE
[Bug]: The setting of password in RDB adapter is wrong

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase-doc#340]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
The setting of password in RDB adapter is wrong
```

### Fast Reproduce Steps

The setting of password in RDB adapter is wrong

### Actual Behavior

The setting of password in RDB adapter is wrong

**Comment by yuhuangwmn** [comment]
fixed
