### ISSUE TITLE
文档表达准确性建议

### ISSUE THREAD

**Issue by 24kpure** [oceanbase/oceanbase-doc#374]
https://github.com/oceanbase/oceanbase-doc/blob/4aa0ddb6ee97b535f8b50f4ec0ed185b88063a6c/zh-CN/700.reference/400.development-reference/200.sql-specifications-and-practices/300.sql-statement-example/200.join-table-usage-suggestions.md?plain=1#L5

1.中文表述是否存在歧义？
2.文档中中英文符号混用，句号时而`。`，时而`.`

**Comment by lacrimosaprinz** [comment]
您好！
首先，我想对您在 GitHub 上对我们项目所提出的宝贵反馈表示衷心的感谢。我们非常重视您的意见，并已经据此采取了一系列改进措施，以提高项目的可用性和文档的质量。
基于您的反馈，我们已经实施了若干改进。我们承诺会持续精进我们的工作，以满足社区的期望。

关于文档中中文表述的疑问，我们将优化改进我们的中文措辞；关于文档中中文标点符号的指正，我们将对全部版本进行检查纠错。

再次感谢您的参与和支持。

如果您有任何进一步的建议或需要帮助，请随时联系我们。

Best Regards！

**Comment by 24kpure** [comment]
Thanks for your reply.
