### ISSUE TITLE
该图片上的系统表书写错误

### ISSUE THREAD

**Issue by ChrisYuan** [oceanbase/oceanbase-doc#53]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/2404284/164945052-d8b45a3d-932d-4b46-9368-531850e14649.png">

链接地址：https://help-static-aliyun-doc.aliyuncs.com/assets/img/zh-CN/4462752461/p356007.jpg

这个图片上系统表前应该是双下划线，我这边没法提交更改，还请稍作修改。

**Comment by MeinaWang** [comment]
问题已修复，https://open.oceanbase.com/docs/observer-cn/V3.1.3/0000000000161702
