### ISSUE TITLE
OceanBase 数据库 TPC-H 测试 一文中，修改query的步骤不完整

### ISSUE THREAD

**Issue by yangzhifeng** [oceanbase/oceanbase-doc#8]
原文中写道：“
  去掉生成文件中的 limit -xx（OB不支持limit 负数的语法） , 去掉 day 后的 (3), 加上parallel(96) 并发
”

实际上只这样做是不够的，还需要
1. 某些非负数的limit 100，要去掉limit前面的;
2. 更关键的，q13需要修改语法，否则会报错You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near '(c_custkey, c_count)

**Comment by Xjxjy** [comment]
查询 SQL 可参考该链接：https://github.com/oceanbase/obdeploy/tree/master/plugins/tpch/3.1.0/queries

**Comment by MeinaWang** [comment]
在文档中添加了生成的查询 SQL 的链接，用户可以选择自己生成后参考给出的 SQL 进行调整，也可以选择直接复制已经给出的查询 SQL。https://open.oceanbase.com/docs/observer-cn/V3.1.3/10000000000096610
